[book]
authors = ["ぞぞかす","くろん"]
language = "jp"
multilingual = false
src = "src"
title = "Resonite 非公式日本語ガイドブック"
[output.html]
additional-js = ["assets/fzf.umd.js", "assets/elasticlunr.js", "theme/custom.js","theme/pagetoc.js"]
additional-css = ["theme/custom.css", "theme/pagetoc.css"]
[preprocessor.callouts]