name: deploy

on:
  push:
    paths:
      - "resonite-tutorial/src/**"
      - "resonite-tutorial/book.toml"
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      statuses: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install latest mdbook
      run: |
        tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
        url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
        mkdir mdbook
        curl -sSL $url | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH

    - name: Install latest mdbook-utils
      run:
        cargo install --git https://github.com/john-cd/mdbook-utils dependencies
        
    - name: Build Book
      run: |
        # This assumes your book is in the root of your repository.
        # Just add a `cd` here if you need to change to another directory.
        cd resonite-tutorial
        mdbook build
        mdbook-utils sitemap -b https://resonite-jp-guide.zozoka.su/
        
    - name: Publish to Cloudflare Pages
      id: resonite_jp_guide
      uses: cloudflare/pages-action@1
      with:
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        projectName: resonite-jp-guide
        directory: ./resonite-tutorial/book
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Add publish URL as commit status
      uses: actions/github-script@v6
      with:
        script: |
          const sha = context.payload.pull_request?.head.sha ?? context.sha;
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            context: 'Cloudflare Pages',
            description: 'Cloudflare Pages deployment',
            state: 'success',
            sha,
            target_url: "${{ steps.resonite_jp_guide.outputs.url }}",
          });
